### ISSUE TITLE
Output is all zeros

### ISSUE THREAD

**Issue by wooahn** [ome/ome-zarr-py#201] opened 2022-05-20 17:13 UTC
Hello, whenever I open a zarr with a single YX image using this plugin, the output is all zeros, and the view is completely black. Without the plugin, the image is correctly rendered.

Here is the code to reproduce:

```python
from pathlib import Path

import napari
import numpy as np
import skimage.data
import zarr
from ome_zarr.writer import write_image


def make_test_zarr(path: Path):
    data = skimage.data.astronaut()
    data = data[..., 0]

    root = zarr.group(path, overwrite=True)
    root.attrs.clear()
    write_image(data, root, axes=["y", "x"])


def view_test_zarr(path: Path):
    viewer = napari.Viewer()
    viewer.open(path, plugin="napari-ome-zarr")
    # viewer.open(path)  # works!
    napari.run()  # output is a black image!


def check(path: Path):
    viewer = napari.Viewer()
    viewer.open(path, plugin="napari-ome-zarr")
    layer = viewer.layers[0]

    print(np.asarray(layer.data[0]))  # all zeros!


if __name__ == "__main__":
    path = Path("test-astronaut.zarr")
    make_test_zarr(path)
    view_test_zarr(path)
    # check()
```

And here is my python environment:
```
napari: 0.4.15
Platform: Linux-5.13.0-41-generic-x86_64-with-glibc2.29
System: Ubuntu 20.04.4 LTS
Python: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
Qt: 5.15.2
PySide2: 5.15.2.1
NumPy: 1.22.3
SciPy: 1.8.1
Dask: 2022.05.0
VisPy: 0.10.0
ome-zarr: 0.4.1

OpenGL:
- GL version: 4.6.0 NVIDIA 510.73.05
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0

Plugins:
- console: 0.0.4
- napari-ome-zarr: 0.4.0
- scikit-image: 0.4.15
- svg: 0.1.6
```

**Comment by sbesson** [comment] 2022-05-23 12:29
Thanks @wooahn for the code allowing to reproduce your issue. Looking at the data that is generated by the writer bit,

```
test-astronaut.zarr
test-astronaut.zarr/.zattrs
test-astronaut.zarr/.zgroup
test-astronaut.zarr/0
test-astronaut.zarr/0/.zarray
test-astronaut.zarr/0/1.0
test-astronaut.zarr/0/0.0
test-astronaut.zarr/1
test-astronaut.zarr/1/.zarray
test-astronaut.zarr/1/0.0
test-astronaut.zarr/4
test-astronaut.zarr/4/.zarray
test-astronaut.zarr/4/0.0
test-astronaut.zarr/3
test-astronaut.zarr/3/.zarray
test-astronaut.zarr/3/0.0
test-astronaut.zarr/2
test-astronaut.zarr/2/.zarray
test-astronaut.zarr/2/0.0
```

the issue is that the chunks are written using `.` as the dimension separator instead of `/` which is the new requirement since version 0.2 of the OME-NGFF specification.

Updating the sample to use the code path suggested as  https://ome-zarr.readthedocs.io/en/stable/python.html#writing-ome-ngff-images

```diff
7a8
> from ome_zarr.io import parse_url
13,14c14,15
< 
<     root = zarr.group(path, overwrite=True)
---
>     store = parse_url(path, mode="w").store
>     root = zarr.group(store=store, overwrite=True)
```

fixes the data writing and the reading using `napari` so hopefully this should unblock you. 

@joshmoore @will-moore are we expecting to support this scenario (i.e. creating the root directly using `zarr.group`) ? If not, is there a case for adding a sanity mechanism e.g. in `write_image` allowing to detect that the store was not initialized according to the requirements of the specification?

**Comment by will-moore** [comment] 2022-05-23 15:51
@sbesson I guess `write_image()` could do:
```
assert group.store._dimension_separator == "/"
```
but if you're writing version 0.1 data then that would fail.
The handling of `dimension_separator` for different versions is within `Format.init_store` and isn't accessible outside of that.

**Comment by joshmoore** [comment] 2022-06-24 10:58
I'm going to assume it's alright to close this but please let me know if that's not the case.

**Closed by joshmoore** 2022-06-24 10:58 UTC
